### ISSUE TITLE
Should Microsoft be inserting a repo that is lexically ahead of the distro one?

### ISSUE THREAD

**Issue by ChrisRitson** [newcastleuniversity/puppet_module_microsoft_defender_atp_agent#4]
If this module generates a list file in sources.d called "microsoft.list" this allows them to override manufacturer's dirstor. Is this desirable?

[Sources_d.txt](https://github.com/newcastleuniversity/puppet_module_microsoft_defender_atp_agent/files/8026153/Sources_d.txt)

**Comment by threepistons** [comment]
What is a dirstor?

**Comment by threepistons** [comment]
@ChrisRitson I suspect that you are thinking of the various packages that have 10-highpriority.stub, 20-notashigh.stub, 99-dothislast.stub in their foo.conf.d directories to make things happen in a particular order.  [Apt uses pinning](https://wiki.debian.org/AptConfiguration?action=show&redirect=AptPreferences#apt_preferences_.28APT_pinning.29), not sort order of the files in sources.list.d, to prioritise package sources.  Please have a look at the pinning docs linked and let me if I've guessed correctly.

**Comment by ChrisRitson** [comment]
I was thinking purely in lexicographic order of files in sources.list.d. If Microsoft have not abused the priority/pinning mechanism then this can be closed. If they are abusing this mechanism because "Microsoft Knows Best" then this could raise issues.
